Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
Pull total number of customers that purchased in January 2023 and the average amount spend per customer
Pull the departments that generated less than $600 in 2022
What is the most and least revenue we have generated by an order
What were the orders that were purchased in our most lucrative order
